// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3nH37eeSbadc1AxcHlrIHgqy0S8ZV9YM',
    appId: '1:551897697221:web:55bca474b5837b3c1999ac',
    messagingSenderId: '551897697221',
    projectId: 'midias-uploader',
    authDomain: 'midias-uploader.firebaseapp.com',
    storageBucket: 'midias-uploader.appspot.com',
    measurementId: 'G-XSYZLFGBP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi6Ulw3rmM1G3rv2WXoB4tCCc8VdXLAxo',
    appId: '1:551897697221:android:c93ac3d5f396868f1999ac',
    messagingSenderId: '551897697221',
    projectId: 'midias-uploader',
    storageBucket: 'midias-uploader.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBymWUx1O9GpD8nX6ZPgZIOXPg37FqZuis',
    appId: '1:551897697221:ios:77eadee30753113f1999ac',
    messagingSenderId: '551897697221',
    projectId: 'midias-uploader',
    storageBucket: 'midias-uploader.appspot.com',
    iosBundleId: 'com.example.mobiResizeImageFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBymWUx1O9GpD8nX6ZPgZIOXPg37FqZuis',
    appId: '1:551897697221:ios:77eadee30753113f1999ac',
    messagingSenderId: '551897697221',
    projectId: 'midias-uploader',
    storageBucket: 'midias-uploader.appspot.com',
    iosBundleId: 'com.example.mobiResizeImageFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3nH37eeSbadc1AxcHlrIHgqy0S8ZV9YM',
    appId: '1:551897697221:web:5ddeccca3398391b1999ac',
    messagingSenderId: '551897697221',
    projectId: 'midias-uploader',
    authDomain: 'midias-uploader.firebaseapp.com',
    storageBucket: 'midias-uploader.appspot.com',
    measurementId: 'G-Z27N4JZ8BM',
  );
}
